
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SekkaWahda.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Car
{

    public int ID { get; set; }

    public string CarModel { get; set; }

    public string carColor { get; set; }

    public string CarImagePath { get; set; }

    public Nullable<int> UserId { get; set; }

    public string CarImageRelativeUrl { get; set; }

    public string CarLicense { get; set; }



    public virtual UserMaster UserMaster { get; set; }

}

}
