
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SekkaWahda.Models
{

using System;
    using System.Collections.Generic;
    
public partial class notification_
{

    public int NotificationID { get; set; }

    public Nullable<int> ReceiverID { get; set; }

    public Nullable<int> RaiserID { get; set; }

    public string Message_ { get; set; }

    public string TypeOfNotification { get; set; }



    public virtual UserMaster UserMaster { get; set; }

}

}
