
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SekkaWahda.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Rating
{

    public int RatingId { get; set; }

    public Nullable<int> TravellerId { get; set; }

    public Nullable<int> DriverId { get; set; }

    public Nullable<byte> RateValue { get; set; }



    public virtual UserMaster UserMaster { get; set; }

}

}
