
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SekkaWahda.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserMaster()
    {

        this.Reservations = new HashSet<Reservation>();

        this.trips = new HashSet<trip>();

        this.Cars = new HashSet<Car>();

        this.Ratings = new HashSet<Rating>();

        this.notification_ = new HashSet<notification_>();

    }


    public int UserID { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public string UserRoles { get; set; }

    public string UserEmailID { get; set; }

    public string city { get; set; }

    public string SSN { get; set; }

    public string DriverLicense { get; set; }

    public string FullName { get; set; }

    public string imagePath { get; set; }

    public string PhoneNumber { get; set; }

    public string ImageUrl { get; set; }

    public Nullable<decimal> DriverTotalRate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reservation> Reservations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<trip> trips { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Car> Cars { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rating> Ratings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<notification_> notification_ { get; set; }

}

}
